import { FateCard } from './fateCards.model';

const fateCards: FateCard[] = [
  {
    picts_direction: 'right',
    goods: 3,
    gladiator: 2,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    goods: 2,
    gladiator: 1,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'yellow',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    goods: 1,
    gladiator: 1,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    goods: 2,
    gladiator: 1,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    goods: 2,
    gladiator: 2,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    goods: 4,
    gladiator: 2,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    goods: 3,
    gladiator: 3,
    resource: [
      'black',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    goods: 3,
    gladiator: 3,
    resource: [
      'black',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    goods: 1,
    gladiator: 3,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    goods: 4,
    gladiator: 2,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    goods: 6,
    gladiator: 1,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
    ],
  },
  {
    picts_direction: 'center',
    goods: 3,
    gladiator: 2,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    goods: 2,
    gladiator: 1,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
    ],
  },
  {
    picts_direction: 'right',
    goods: 5,
    gladiator: 2,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    goods: 2,
    gladiator: 2,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    goods: 1,
    gladiator: 1,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'yellow',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    goods: 5,
    gladiator: 2,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    gladiator: 2,
    goods: 1,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    gladiator: 2,
    goods: 1,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    gladiator: 3,
    goods: 4,
    resource: [
      'black',
      'blue',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    gladiator: 3,
    goods: 4,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    gladiator: 1,
    goods: 6,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    gladiator: 1,
    goods: 1,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    gladiator: 3,
    goods: 2,
    resource: [
      'black',
      'blue',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    gladiator: 1,
    goods: 6,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'yellow',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    gladiator: 2,
    goods: 1,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    gladiator: 1,
    goods: 1,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
    ],
  },
  {
    picts_direction: 'right',
    gladiator: 1,
    goods: 6,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    gladiator: 1,
    goods: 4,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'yellow',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    gladiator: 2,
    goods: 3,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    gladiator: 1,
    goods: 2,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    gladiator: 3,
    goods: 5,
    resource: [
      'black',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    gladiator: 1,
    goods: 4,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
    ],
  },
  {
    picts_direction: 'left',
    gladiator: 3,
    goods: 3,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    gladiator: 2,
    goods: 1,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    gladiator: 2,
    goods: 1,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    gladiator: 1,
    goods: 4,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    gladiator: 2,
    goods: 3,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    gladiator: 3,
    goods: 1,
    resource: [
      'black',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    gladiator: 3,
    goods: 2,
    resource: [
      'black',
      'black',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    gladiator: 3,
    goods: 3,
    resource: [
      'black',
      'blue',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    gladiator: 2,
    goods: 2,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    gladiator: 1,
    goods: 4,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    gladiator: 2,
    goods: 2,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    gladiator: 2,
    goods: 5,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'center',
    gladiator: 3,
    goods: 2,
    resource: [
      'black',
      'blue',
      'purple',
      'purple',
      'purple',
      'yellow',
      'yellow',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    gladiator: 3,
    goods: 1,
    resource: [
      'black',
      'blue',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'left',
    gladiator: 2,
    goods: 3,
    resource: [
      'black',
      'black',
      'blue',
      'blue',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
  {
    picts_direction: 'right',
    gladiator: 2,
    goods: 2,
    resource: [
      'black',
      'blue',
      'blue',
      'purple',
      'purple',
      'yellow',
      'brick',
      'brick',
    ],
  },
];

export default fateCards;
